from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import sys


def write_version_file(version: str) -> None:
    """Write the current semantic-release version to version.py."""
    project_root = Path(__file__).resolve().parents[1]
    target_path = project_root / "src/version.py"

    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    content = (
        "\"\"\"\n"
        "This file is auto-generated by semantic-release.\n"
        "Do not edit manually.\n"
        "\"\"\"\n\n"
        "__all__ = ['__version__', '__release_date__']\n\n"
        f"__version__ = '{version}'\n"
        f"__release_date__ = '{timestamp}'\n"
    )

    target_path.write_text(content, encoding="utf-8")


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("Usage: write_version_file.py <version>")

    version = sys.argv[1]
    write_version_file(version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
